name: CI for KenPile

on: 
  push:
    branches: 
      - dev

jobs:
  deploy:
    name: Push to dev--heroku branch and keep only server directory
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dev--heroku
          FOLDER: server
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}